spring.application.name=06_mini_project

sever.port=4041
server.servlet.context-path=/app




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#oracle---------------
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb
spring.datasource.username=FIRSTDB
spring.datasource.password=123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver